apiVersion: v1
kind: Service
metadata:
  name: tfserving
  namespace: iot-anomaly
spec:
  ports:
    - name: rest
      port: 8501
      targetPort: 8501
    - name: grpc
      port: 8500
      targetPort: 8500
  selector:
    app: tfserving
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving
  namespace: iot-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfserving
  template:
    metadata:
      labels:
        app: tfserving
    spec:
      containers:
        - name: tfserving
          image: tensorflow/serving:2.14.0
          args:
            - "--model_base_path=/models/anomaly_detector"
            - "--rest_api_port=8501"
          env:
            - name: MODEL_NAME
              value: "anomaly_detector"
          ports:
            - containerPort: 8501
            - containerPort: 8500
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          emptyDir: {}
